version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
      - docker build -t bookit-api:build .

artifacts:
  files:
    - build/libs/bookit-api-0.0.1-SNAPSHOT.jar
