version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk

  pre_build:
    commands:
      - $(aws ecr get-login --region us-east-1)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"

  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew build
      - docker build --tag "${REPOSITORY_URI}:${TAG}" .

  post_build:
    commands:
      - test $CODEBUILD_BUILD_SUCCEEDING -eq 0 || docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s"}' $TAG > build.json

artifacts:
  files:
    - build.json
