---

management:
  context-path: /management
security:
  user:
    name: admin
    password: ${bookit.admin.password:password}
springfox:
  documentation.swagger.v2.path: /api-docs
spring:
  jackson:
    serialization.write-dates-as-timestamps: false
    default-property-inclusion: non_absent
  datasource:
    name: bookit
    username: ${bookit.database.user:}
    password: ${bookit.database.password:}
    url: ${bookit.database.url:}
    driver-class-name: ${bookit.database.driver:}
okta:
  oauth2:
    issuer: https://dev-621718.oktapreview.com/oauth2/default
    clientId: 0oad25jpgsJEyvhpQ0h7
    audience: api://default
logging:
  level:
    org.springframework.security: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
