---

management:
  context-path: /management
security:
  user:
    name: admin
    password: ${bookit.admin.password:password}
springfox:
  documentation.swagger.v2.path: /api-docs
spring:
  jackson:
    serialization.write-dates-as-timestamps: false
    default-property-inclusion: non_absent
  datasource:
    name: bookit
    username: ${bookit.database.user:}
    password: ${bookit.database.password:}
    url: ${bookit.database.url:}
    driver-class-name: ${bookit.database.driver:}
  jpa:
    database-platform: ${bookit.database.dialect:}
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  logging:
    level:
#      org.hibernate.SQL: DEBUG
#      org.springframework.security: DEBUG
#      org.springframework.web.client.RestTemplate: DEBUG
